path_classifiers:
  library:
    - fmt
    - mdcomp
extraction:
  cpp:
    after_prepare:
      - mkdir custom_cmake
      - wget --quiet -O - "http://www.cmake.org/files/v3.20/cmake-3.20.3-linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C custom_cmake
      - export PATH=$(pwd)/custom_cmake/bin:${PATH}
