language: cpp

dist: xenial
sudo: required
compiler: gcc

cache:
    directories:
        - ${TRAVIS_BUILLD_DIR}/deps

addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_depends
      - libboost-all-dev

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "CMUqnjv2zeT3hVL/4993ylZvmsDfT1sLzh3r05YJ2Bcyxhtw/7Aw/DEKFk7bGH8GP4ofYZ8IGT5GpndCkRByZKhxvoDwuoCSr1IyyH9yY+ZixAJQxn/Bdo1yn97hc2WLrFYtjqXNcsZzstqXDFgVUYUTaGnNwHtH0dhHFBXTQdrW6/QW6y9WNOukK5/w5TvADvjbz8vI7LCTtxo+USuFSmfFxJr9lCpLSnYxK/XATTrKspibIZRYImUqvHil3xMRowLt+6I+eTLE5itHq4r6gOx/INKoMN9N+M7sTQW2WTQQUDQKLkOPNEygQV7nCAgmlBBpS2sb+db01MMUWJxtWyqTPjBu9bTVicCo24/4FLSNLngL267SaHrZsvcrj4//f9iND4ZO6ghqUZT3AbLXhjKHTIzcb2q3Ou3E25t1+B0rPW49ni+RwunB6Q1h4XFsrj90eqkE4I6Zb8+2/Myo+U/1w2eKodr4qppwG2jspqpAn6LGaWkK2gIPoBK9rODMxCUy11LxF94okGPZbAyy8Hya8Yu8DgLds/ukx22AFFt2PbtQb+Tk5TypA257he+h6UC2ocfMbLq+zRYy40VEHO4UWN8NNOx1Bk9Tk2wgB51SSoSuSqjav5E6kEw3sfXUfr/455tN+7WvvnADkV8OO4VYSgrHHoy/bhk3tupmYeI="
    - MAKEFLAGS="-j 2"

matrix:
    include:
        ##########################################################################
        # Coverity with GCC on Linux
        ##########################################################################
        - os: linux
          compiler: gcc
          env: MATRIX_EVAL="export CXX=g++ && export CC=gcc" DO_COVERITY=1
          addons:
            apt:
              sources: *common_sources
              packages:
                - *common_depends
                - g++-7
            coverity_scan:
              project:
                name: "flamewing/mdtools"
                description: "Assorted tools for the Sega Mega Drive"
              notification_email: flamewing.sonic@gmail.com
              build_command_prepend: "./autogen.sh"
              build_command: "make"
              branch_pattern: coverity_scan
          before_script:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1000
            - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1000
            - pushd `mktemp -d` && git clone --depth 1 https://github.com/flamewing/mdcomp.git && cd mdcomp && ./autogen.sh && make && sudo make install && popd

        ##########################################################################
        # clang on Linux
        ##########################################################################
        - os: linux
          compiler: clang
          env: MATRIX_EVAL="export CXX=clang++ && export CC=clang" DO_COVERITY=0
          addons:
            apt:
              sources: llvm-toolchain-xenial-7
              packages:
                - *common_depends
                - clang-7
          before_script:
            - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 1000
            - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 1000
            - pushd `mktemp -d` && git clone --depth 1 https://github.com/flamewing/mdcomp.git && cd mdcomp && ./autogen.sh && make && sudo make install && popd

        ##########################################################################
        # GCC on Linux
        ##########################################################################
        - os: linux
          compiler: gcc
          env: MATRIX_EVAL="export CXX=g++ && export CC=gcc" DO_COVERITY=0
          addons:
            apt:
              sources: *common_sources
              packages:
                - *common_depends
                - g++-7
          before_script:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1000
            - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1000
            - pushd `mktemp -d` && git clone --depth 1 https://github.com/flamewing/mdcomp.git && cd mdcomp && ./autogen.sh && make && sudo make install && popd

        - os: linux
          compiler: gcc
          env: MATRIX_EVAL="export CXX=g++ && export CC=gcc" DO_COVERITY=0
          addons:
            apt:
              sources: *common_sources
              packages:
                - *common_depends
                - g++-8
          before_script:
            - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 1000
            - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 1000
            - pushd `mktemp -d` && git clone --depth 1 https://github.com/flamewing/mdcomp.git && cd mdcomp && ./autogen.sh && make && sudo make install && popd

before_install:
  # Exit immediately if the branch is the "coverity_scan" branch and DO_COVERITY is "0"
  - if [ "$TRAVIS_BRANCH" == "coverity_scan" -a "${DO_COVERITY}" == "0" ] ; then exit 0; fi
  # Exit immediately if the branch is not the "coverity_scan" branch and DO_COVERITY is "1"
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_BRANCH" != "coverity_scan" -a "${DO_COVERITY}" == "1" ] ; then exit 0; fi
  - if [ "${DO_COVERITY}" == "1" ]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi

script: if [ "$TRAVIS_BRANCH" != "coverity_scan" ]; then .travis/script.sh; elif [ -e cov-int/scm_log.txt ] ; then cat cov-int/scm_log.txt; fi

notifications:
  email: true
  on_success: change
  on_failure: always

